import type { Module } from '@/lib/types';

export const initialModules: Omit<Module, 'id'>[] = [
  {
    yard: 'TCNMK',
    location: 'GOP',
    moduleNo: 'GH5100-PAR-11',
    rfloDate: '2025-01-10',
    shipmentNo: 'Ship #1',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'WASCO',
    location: 'DC1',
    moduleNo: 'GH0187-SS-001',
    rfloDate: '2026-01-20',
    shipmentNo: 'Ship #3',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'WASCO',
    location: 'DC1',
    moduleNo: 'GH0187-IE-101',
    rfloDate: '2026-01-22',
    shipmentNo: 'Ship #3',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: true,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-07',
    rfloDate: '2026-02-20',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-08',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-09',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-10',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-05',
    rfloDate: '2026-03-05',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '27.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-06',
    rfloDate: '2026-03-05',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '28.11.2025 FAIS IN PROGRESS',
    signedReport: true,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-11',
    rfloDate: '2026-03-06',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-03',
    rfloDate: '2026-03-23',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-01',
    rfloDate: '2026-03-24',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '25.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-02',
    rfloDate: '2026-03-31',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-04',
    rfloDate: '2026-03-31',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '27.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0101-PAU-01',
    rfloDate: '2026-04-30',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-02',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-50',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-TOP-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-BRG-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
  {
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-JKT-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    signedReport: false,
  },
];
