import type { Module } from '@/lib/types';

export const initialModules: Omit<Module, 'isAnomaly' | 'anomalyExplanation'>[] = [
  {
    id: '1',
    yard: 'TCNMK',
    location: 'GOP',
    moduleNo: 'GH5100-PAR-11',
    rfloDate: '2025-01-10',
    shipmentNo: 'Ship #1',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '2',
    yard: 'WASCO',
    location: 'DC1',
    moduleNo: 'GH0187-SS-001',
    rfloDate: '2026-01-20',
    shipmentNo: 'Ship #3',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '3',
    yard: 'WASCO',
    location: 'DC1',
    moduleNo: 'GH0187-IE-101',
    rfloDate: '2026-01-22',
    shipmentNo: 'Ship #3',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '4',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-07',
    rfloDate: '2026-02-20',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '5',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-08',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '6',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-09',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '7',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-10',
    rfloDate: '2026-02-28',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '8',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-05',
    rfloDate: '2026-03-05',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '27.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '9',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-06',
    rfloDate: '2026-03-05',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '28.11.2025 FAIS IN PROGRESS',
    byWhom: '',
  },
  {
    id: '10',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-11',
    rfloDate: '2026-03-06',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '11',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-03',
    rfloDate: '2026-03-23',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '12',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-01',
    rfloDate: '2026-03-24',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '25.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '13',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-02',
    rfloDate: '2026-03-31',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '14',
    yard: 'TCNMK',
    location: 'DC1',
    moduleNo: 'GH0100-PAR-04',
    rfloDate: '2026-03-31',
    shipmentNo: '1st Quarter-2026',
    rfloDateStatus: 'Date Confirmed',
    yardReport: '27.11.2025 PRADEEP IN PROGRESS',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '15',
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0101-PAU-01',
    rfloDate: '2026-04-30',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '16',
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '17',
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-02',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '18',
    yard: 'FABTECH',
    location: 'DC1',
    moduleNo: 'GH0100-PAS-50',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '19',
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-TOP-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '20',
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-BRG-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
  {
    id: '21',
    yard: 'NPCC',
    location: 'DC1',
    moduleNo: 'GH0100-JKT-01',
    rfloDate: '',
    shipmentNo: '',
    rfloDateStatus: 'Pending',
    yardReport: '',
    islandReport: '',
    byWhom: '',
  },
];
